### ISSUE TITLE
Symbols issue

### ISSUE THREAD

**Issue by skiank** [jbrunken/ActiveForumsTapatalk#1]
On some forum some symbols as à,è,i.... not appear correctly. 
TT client show: &#xxx;

**Comment by skiank** [comment]
Just installed V1.0 pre-release. Symbols are now correct on Windows 8 Phone TT App too!
Great!

**Comment by skiank** [comment]
On My WP8 html tags are not hidden and smiles appear with the code ":_smile:" etc.
I don't remember if you this or not

**Comment by jbrunken** [comment]
Smile features aren't supported yet.
