### ISSUE TITLE
Bug with iPhone app version 2.5.2 - replying to a post crashes app

### ISSUE THREAD

**Issue by supermansrf** [jbrunken/ActiveForumsTapatalk#10]
I can't confirm this on other versions or with other platforms, but there is most definitely an issue replying with this version of tapatalk.  I can also confirm that this is only happening on the few sites I'm using with the tapatalk plugin for active forums.  It does not exist on other non DNN forums.  

When I reply to a topic from the app it actually posts to the forum (99% of the time) but the app crashes.  Then when I go back into the forum on the app, my previous text is still in the input box and needs to be cleared before I can type anything new.  

Creating a new post does not crash the app.  Only replying.

**Comment by supermansrf** [comment]
So I have some more information on this.  When using the quick reply feature I experience the above issue. When I post a full reply using the reply button first it does not happen.  Anyone else seeing this?  I'm getting complaints on 3 different sites now but it all seems to be Android only.

**Comment by jbrunken** [comment]
I've already reported this issue to the people at Tapatalk.  Not sure what more I can do.   The crash is happening in the app, not the Tapatalk plugin.   Unfortunately, I have no insight into why the app crashes.

**Comment by supermansrf** [comment]
I can tell you for sure that I only see this issue on AF forums. I participate (rarely) in a few that are not DNN based sites. I don't see the same issue with them. Only my AF sites. 

I replied to a few posts tonight on them just to see what happens and it does not crash. Not sure if this helps or not. 

I'll try to see if I can dig into any logs and see if I can find anything. My iPhone is jailbroken and I have access to the file system. I'll see if I can figure out a way to dig in on my phone.

**Comment by supermansrf** [comment]
This has been somewhat resolved by an update to the iOS app. Refer to issue #5 which will include a fix for the quick reply bug shortly.
